# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export TERM=xterm-256color

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# history
export HISTCONTROL=ignoreboth
export HISTFILESIZE=100000
export HISTSIZE=100000
export HISTIGNORE="ls:ll:jj:bg:fg"
#shopt -s histappend
#export PROMPT_COMMAND='history -a'

 #check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi

PS1='(\t)\u@\h:\w\n$ '

unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# Aliases

alias ll='ls -l'
alias wcl='wc -c'
alias hh='history 25'
alias jj='jobs -l'
alias lp='lp -o media=a4'
alias mysql='mysql --default-character-set=utf8'
alias awkt='awk -F"\t" -v OFS="\t"'
alias mawkt='mawk -F"\t" -v OFS="\t"'
alias tsort='LC_ALL=C sort -t"	" -T.'
alias tjoin='LC_ALL=C join -t"	"'
alias w2u='iconv -fcp1251 -tutf8'

# Ya-specific
alias ya='~/ya'


# BM-specific
alias bmup='sudo -u bmclient svn --username=malykhin update'
alias cdbm='cd /opt/broadmatching'
alias subm='sudo -u bmclient bash'

# Functions
function tex2pdf() {
    name=${1%.tex}
    latex $name.tex && latex $name.tex && dvips $name.dvi && ps2pdf $name.ps;
}
function grepsrc() {
    find . -name '*.pl' -o -name '*.pm' -o -name '*.tmpl' | xargs grep -H -n "$1" ;
}
function fullpath() {
    echo `/etc/hostname`:`readlink -m $1`;
}
function bmssh() {
    if [[ $1 == "bmdev" ]];
        then screen -t dev ssh bmgen-dev01e.yandex.ru;
    elif [[ $1 == "bmfront" ]];
        then screen -t bmfront ssh bmfront01f.yandex.ru;
    elif [[ $1 == "bmfront01f" ]];
        then screen -t bmfront ssh bmfront01f.yandex.ru;
    else
        screen -t $1 ssh -t bmfront01f.yandex.ru ssh $1.yandex.ru;
    fi
}

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

export EDITOR=vim
export BMR=/opt/broadmatching

# for WEKA
export CLASSPATH=/usr/share/java/weka.jar

# for deb packages signing
export DEBFULLNAME="Yuri Malykhin"
alias dch='dch --distributor=debian'

# python3 startup
#export PYTHONSTARTUP=~/.py3_startup

MYBASHRCDIR=~/.bashrc.d
if [ -d $MYBASHRCDIR ]; then
    for file in $(ls $MYBASHRCDIR); do
        source $MYBASHRCDIR/$file;
    done
fi
